<a href="https://colab.research.google.com/github/Ksenia-90/linear_algebra/blob/lesson_3/lesson_3_DZ_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
np.set_printoptions(precision=2, suppress=True)


__1.__ Найти собственные векторы 

и собственные значения для линейного оператора, заданного матрицей

$$A=\begin{pmatrix}
-1 & -6\\ 
2 & 6
\end{pmatrix}.$$


In [2]:
def is_eig(A):
    w, v = np.linalg.eig(A)
    print(f'Матрица A:\n{A}')
    print(f'Собственные значения:\n{w}')
    print(f'Собственные векторы:\n{v}')

In [3]:
A = np.array([[-1, -6], [2, 6]])
is_eig(A)

Матрица A:
[[-1 -6]
 [ 2  6]]
Собственные значения:
[2. 3.]
Собственные векторы:
[[-0.89  0.83]
 [ 0.45 -0.55]]


__2.__ Дан оператор поворота на 180 градусов, задаваемый матрицей 

$$A=\begin{pmatrix}
-1 & 0\\ 
0 & -1
\end{pmatrix}.$$

Показать, что __любой__ вектор является для него собственным.


λ = -1
* Верно для любого вектора

__3.__ Пусть линейный оператор задан матрицей

$$A=\begin{pmatrix}
1 & 1\\ 
-1 & 3
\end{pmatrix}.$$

Установить, является ли вектор $x=(1,1)$ собственным вектором этого линейного оператора.



$$
$$$$\begin{cases}
1+1=1\cdot\lambda \\ 
-1+3 = 1\cdot \lambda
\end{cases}
\Rightarrow
\begin{cases}
\lambda=2\\ 
\lambda=2
\end{cases}.$$

In [4]:
A = np.array([[1, 1], [-1, 3]])
is_eig(A)

Матрица A:
[[ 1  1]
 [-1  3]]
Собственные значения:
[2. 2.]
Собственные векторы:
[[ 0.71 -0.71]
 [ 0.71 -0.71]]


Вектор $x$ является собственным вектором линейного оператора, заданного матрицей $A$.

**4.** Пусть линейный оператор задан матрицей

$$A=\begin{pmatrix} 0 & 3 & 0\\ 3 & 0 & 0\\ 0 & 0 & 3 \end{pmatrix}.$$

Установить, является ли вектор $x=(3, -3, -4)$ собственным вектором этого линейного оператора.

In [5]:
A = np.array([[0, 3, 0], [3, 0, 0], [0, 0, 3]])
is_eig(A)

Матрица A:
[[0 3 0]
 [3 0 0]
 [0 0 3]]
Собственные значения:
[ 3. -3.  3.]
Собственные векторы:
[[ 0.71 -0.71  0.  ]
 [ 0.71  0.71  0.  ]
 [ 0.    0.    1.  ]]



$$$$\begin{cases}
-9=3\cdot\lambda \\ 
9=-3\cdot\lambda \\ 
-12=-4\cdot \lambda
\end{cases}

\begin{cases}
\lambda=-3\\ 
\lambda=-3\\ 
\lambda=3
\end{cases}.