<a href="https://colab.research.google.com/github/Ksenia-90/linear_algebra/blob/lesson_4/lesson_4_DZ_7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

__1.__ Решить систему уравнений методом Крамера:

   а) $\begin{cases}
x_{1}-2x_{2}=1 \\
3x_{1}-4x_{2}=7
\end{cases}$
    
   б) $\begin{cases}
2x_{1}-x_{2}+5x_{3}=10 \\
x_{1}+x_{2}-3x_{3}=-2 \\
2x_{1}+4x_{2}+x_{3}=1
\end{cases}$

In [ ]:
import numpy as np

A = np.array([[1, -2], [3, -4]])
b = np.array([1, 7]).reshape(-1, 1)

x1 = np.linalg.det(np.hstack((b, A[:,1].reshape(-1, 1)))) /  np.linalg.det(A)
x1

4.999999999999998

In [ ]:
x2 = np.linalg.det(np.hstack((A[:,0].reshape(-1, 1), b))) /  np.linalg.det(A)
x2

1.9999999999999991

In [ ]:
np.linalg.solve(A, b)

array([[5.],
       [2.]])

In [ ]:
B= np.array([[2, -1, 5], [1, 2, -3], [2, 4, 1]])
b = np.array([10, -2, 1]).reshape(-1, 1)

In [ ]:
x_1 = np.linalg.det(np.hstack((b, B[:,1:]))) /  np.linalg.det(B)
x_1

2.6000000000000023

In [ ]:
x_2 = np.linalg.det(np.hstack((B[:,:1], b, B[:,-1:]))) /  np.linalg.det(B)
x_2

-1.2285714285714293

In [ ]:
x_3 = np.linalg.det(np.hstack((B[:,:2], b))) /  np.linalg.det(B)
x_3

0.7142857142857143

In [ ]:
np.linalg.solve(B, b)

array([[ 2.6       ],
       [-1.22857143],
       [ 0.71428571]])

$$\begin{pmatrix}
2 & -1 & 5 \\ 
1 & 1 & -3 \\ 
2 & 4 & 1
\end{pmatrix} = 2 + 6 + 20 - 10 + 24 + 1 = 43$$

$$\begin{pmatrix}
10 & -1 & 5 \\ 
-2 & 1 & -3 \\ 
1 & 4 & 1
\end{pmatrix} = 10 + 3 - 40 - 5 + 120 - 2 = 86$$

$$\begin{pmatrix}
2 & 10 & 5 \\ 
1 & -2 & -3 \\ 
2 & 1 & 1
\end{pmatrix} = -4 - 60 + 5 + 20 + 6 - 10 = -43$$

$$\begin{pmatrix}
2 & -1 & 10 \\ 
1 & 1 & -2 \\ 
2 & 4 & 1
\end{pmatrix} = 2 + 4 + 40 - 20 + 16 + 1 = 43$$

Решение руками:
* x_1 = 86/43 = 2
* x_2 = -43/43 = -1
* x_3 = 43/43 =  1


__2*.__ Найти $L$-матрицу $LU$-разложения для матрицы коэффициентов:

   а)$$\begin{pmatrix}
1 & 2 & 4 \\ 
2 & 9 & 12 \\ 
3 & 26 & 30
\end{pmatrix}$$
    
   б)$$\begin{pmatrix}
1 & 1 & 2 & 4\\ 
2 & 5 & 8 & 9\\ 
3 & 18 & 29 & 18\\
4 & 22 & 53 & 33
\end{pmatrix}$$

In [ ]:
from scipy.linalg import lu
import pprint
A = np.array([[1,2,4], [2,9,12], [3,26,30]])
p, l, u = lu(A)
print("L:")
pprint.pprint(l)


L:
array([[1.        , 0.        , 0.        ],
       [0.66666667, 1.        , 0.        ],
       [0.33333333, 0.8       , 1.        ]])


А на листочке ответ вот такой:
$$\begin{pmatrix}
1 & 0 & 0\\ 
2 & 1 & 0 \\ 
3 & 4 & 1
\end{pmatrix}$$


In [ ]:
from scipy.linalg import lu
import pprint
A = np.array([[1,1,2,4], [2,5,8,9], [3,18,29,18], [4,22,53,33]])
p, l, u = lu(A)
print("L:")
pprint.pprint(l)

L:
array([[ 1.        ,  0.        ,  0.        ,  0.        ],
       [ 0.5       ,  1.        ,  0.        ,  0.        ],
       [ 0.75      , -0.25      ,  1.        ,  0.        ],
       [ 0.25      ,  0.75      , -0.17073171,  1.        ]])


А на листочке ответ вот такой:
$$\begin{pmatrix}
1 & 0 & 0 & 0\\ 
2 & 1 & 0 & 0\\ 
3 & 5 & 1 & 0\\
4 & 6 & 7 & 1
\end{pmatrix}$$


__3*.__ Решить систему линейных уравнений методом $LU$-разложения

$$\begin{cases}
2x_{1}+x_{2}+3x_{3}=1 \\
11x_{1}+7x_{2}+5x_{3}=-6 \\
9x_{1}+8x_{2}+4x_{3}=-5
\end{cases}$$

$$\begin{pmatrix}
1 & 0 & 0 \\ 
0 & 1 & 0 \\ 
0 & 0 & 1
\end{pmatrix}$$ 
$$\begin{pmatrix}
2 & 1 & 3 \\ 
11 & 7 & 5 \\ 
9 & 8 & 4
\end{pmatrix}$$

$$U_{21} = 11-(11*2)/2 = 0$$
$$U_{22} = 7-11*1/2 = 3/2$$
$$U_{23} = 5-11*3/2 = -23/2$$
$$L_{21} = 11/2$$
$$U_{31} = 9-9*2/2 = 0$$
$$U_{32} = 8-9*1/2 = 7/2$$
$$U_{33} = 4-9*3/2 = -19/2$$
$$L_{31} = 9/2$$
$$U_{32} = (7/2)*(7/2)*(3/2)/(3/2)=0$$
$$U_{33} = 52/3$$
$$L_{32} = (7/3)$$



Ответ:
$$\begin{pmatrix}
1 & 0 & 0 \\ 
11/2 & 1 & 0 \\ 
9/2 & 7/3 & 1
\end{pmatrix}$$ 
$$\begin{pmatrix}
2 & 1 & 3 \\ 
0 & 3/2 & -23/2 \\ 
0 & 0 & 52/3
\end{pmatrix}$$


__4*.__ Решить систему линейных уравнений методом Холецкого

$$\begin{cases}
81x_{1}-45x_{2}+45x_{3}=531 \\
-45x_{1}+50x_{2}-15x_{3}=-460 \\
45x_{1}-15x_{2}+38x_{3}=193
\end{cases}$$

$$l_{11} = \sqrt{a_{11}} = \sqrt{81} = 9$$
$$l_{21} = a_{21} / l_{11} = -45/9 = -5$$
$$l_{22} = \sqrt{{a_{22}}-l^2_{21}}= \sqrt{{50-(-5^2)}} = 5$$
$$l_{31} = a_{31} / l_{11} = 45/9 = 5$$
$$l_{32} = (a_{32} -(l_{31}*l_{21})) / l_{22} = (-15-(5*(-5)))/5 = 2$$
$$l_{33} = \sqrt{{a_{33}}-l^2_{31}+l^2_{32}}= \sqrt{{38-5^2-2^2}} = 3$$



Ответ: 
$$\begin{pmatrix}
9 & 0 & 0 \\ 
-5 & 5 & 0 \\ 
5 & 2 & 3
\end{pmatrix}$$

__5*.__ Написать на Python программу с реализацией одного из изученных алгоритмов решения СЛАУ.

In [ ]:
def cholesky(A):
    pivot = A[0, 0]
    b = np.mat(A[1:, 0])
    B = A[1:, 1:]
    return B - (b.T * b) / pivot


def L(A):
    n = A.shape[0]
    if n == 1:
        return np.sqrt(A)
    b = np.mat(A[1:, 0])
    pivot = np.sqrt(A[0, 0])
    return np.bmat([
        [np.mat(pivot), np.zeros((1, n - 1))],
        [b.T / pivot, L(cholesky(A))]
    ])


def __main():
    A = np.array([[81, 45, -45], [-45, 50, -15], [45, -15, 38]])
    print(L(A))


if __name__ == '__main__':
    __main()

[[ 9.  0.  0.]
 [-5.  5.  0.]
 [ 5.  2.  3.]]
