<a href="https://colab.research.google.com/github/Ksenia-90/linear_algebra/blob/lesson_2/lesson_2_DZ_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

Все задания рекомендуется делать вручную, затем проверяя полученные результаты с использованием numpy.

1. Установить, какие произведения матриц  AB  и  BA  определены, и найти размерности полученных матриц:

а)  A  — матрица  4×2 ,  B  — матрица  4×2 ;

б)  A  — матрица  2×5 ,  B  — матрица  5×3 ;

в)  A  — матрица  8×3 ,  B  — матрица  3×8 ;

г)  A  — квадратная матрица  4×4 ,  B  — квадратная матрица  4×4 .

* а. Произведение не определено 
* б. Произведение определено, размерность 2х3 
* в. Произведение определено, размерность 8х8 
* г. Произведение определено, размерность 4х4 

    
__2.__ Найти сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$


In [4]:
A = np.array([[1, -2], [3, 0]])
B = np.array([[4, -1], [0, 5]])
print(f'Сумма матриц А и В: \n {A + B} ')
print(f'Произведение матриц А и В: \n {np.dot(A, B)}')
print(f'Произведение матриц B и A: \n {np.dot(B, A)}')

Сумма матриц А и В: 
 [[ 5 -3]
 [ 3  5]] 
Произведение матриц А и В: 
 [[  4 -11]
 [ 12  -3]]
Произведение матриц B и A: 
 [[ 1 -8]
 [15  0]]



__3.__ Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$
    

In [5]:
A = np.array([[1, 7], [3, -6]])
B = np.array([[0, 5], [2, -1]])
C = np.array([[2, -4], [1, 1]])
a = 3
b = 2
c = 4
A_1 = a*A
B_1 = b*B
C_1 = c*C
print(f'Матрица 3*А\n {A_1}')
print(f'Матрица 2*B\n {B_1}')
print(f'Матрица 4*c\n {C_1}')
print(f'Линейная комбинация\n {A_1 - B_1 + C_1}')

Матрица 3*А
 [[  3  21]
 [  9 -18]]
Матрица 2*B
 [[ 0 10]
 [ 4 -2]]
Матрица 4*c
 [[  8 -16]
 [  4   4]]
Линейная комбинация
 [[ 11  -5]
 [  9 -12]]


    
__4.__ Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислить $AA^{T}$ и $A^{T}A$.

In [6]:
A = np.array([[4, 1], [5, -2], [2, 3]])
A_T = A.T
print (A_T)

[[ 4  5  2]
 [ 1 -2  3]]


In [7]:
A.dot(A_T)

array([[17, 18, 11],
       [18, 29,  4],
       [11,  4, 13]])

In [8]:
A_T.dot(A)

array([[45,  0],
       [ 0, 14]])

5*. Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

In [10]:
from itertools import starmap
from operator import mul

A = [[1, -2], [3, 0]]
B = [[4, -1], [0, 5]]

def matrixmul(A, B):
    matrix = tuple(zip(*B))
    for row in A:
        yield [sum(starmap(mul, zip(row, column))) for column in matrix]


if "__main__" == __name__:
    print(list(matrixmul(A, B)))

[[4, -11], [12, -3]]
