<a href="https://colab.research.google.com/github/Ksenia-90/linear_algebra/blob/lesson_5/lesson_5_DZ_8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [23]:
import pprint
import numpy as np
import scipy.linalg
np.set_printoptions(precision=2, suppress=True)

1. Найти с помощью NumPy SVD для матрицы

$$\begin{pmatrix}
1 & 2 & 0\\ 
0 & 0 & 5\\ 
3 & -4 & 2\\ 
1 & 6 & 5\\ 
0 & 1 & 0
\end{pmatrix}.$$

In [24]:
A=np.array([[1,2,0],[0,0,5],[3,-4,2],[1,6,5], [0,1,0]])
U, s, W = np.linalg.svd(A)
V = W.T
D = np.zeros_like(A, dtype=float)
D[np.diag_indices(min(A.shape))] = s
print("U:")
pprint.pprint(U)
print("W:")
pprint.pprint(W)
print(f'Матрица D:\n{D}')


U:
array([[ 0.17,  0.16, -0.53, -0.8 , -0.16],
       [ 0.39, -0.53,  0.61, -0.43,  0.03],
       [-0.14, -0.82, -0.52,  0.14,  0.07],
       [ 0.89,  0.06, -0.25,  0.38, -0.06],
       [ 0.08,  0.11, -0.08, -0.11,  0.98]])
W:
array([[ 0.07,  0.72,  0.69],
       [-0.37,  0.67, -0.65],
       [-0.93, -0.21,  0.31]])
Матрица D:
[[8.82 0.   0.  ]
 [0.   6.14 0.  ]
 [0.   0.   2.53]
 [0.   0.   0.  ]
 [0.   0.   0.  ]]


In [25]:
print(np.dot(V.T, V))

[[ 1.  0. -0.]
 [ 0.  1. -0.]
 [-0. -0.  1.]]


In [26]:
print(np.dot(np.dot(U, D), V.T))

[[ 1.  2.  0.]
 [ 0. -0.  5.]
 [ 3. -4.  2.]
 [ 1.  6.  5.]
 [-0.  1. -0.]]



2. Для матрицы из предыдущего задания найти:

    а) евклидову норму;
    
    б) норму Фробениуса.

In [27]:
A=np.array([[1,2,0],[0,0,5],[3,-4,2],[1,6,5], [0,1,0]])

In [28]:
print(np.linalg.norm(A,ord=2))

8.824868854820444


In [29]:
#Норма Фробениуса
frob_norm = 0
for i in range(np.linalg.matrix_rank(A)):
    frob_norm += S[i]**2
frob_norm = np.sqrt(frob_norm)
frob_norm

11.045361017187261

In [30]:
np.linalg.norm(A, ord='fro')

11.045361017187261