<a href="https://colab.research.google.com/github/Ksenia-90/linear_algebra/blob/lesson_2/lesson_2_DZ_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [18]:
import numpy as np

In [19]:
rank = np.linalg.matrix_rank
inv = np.linalg.inv

Все задания рекомендуется выполнять вручную, затем проверяя полученные результаты с использованием Numpy.

__1.__ Вычислить определитель:

   a)

$$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix};$$

   б)
    
$$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix};$$
    
   в)

$$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix}.$$




a) $sin^{2}x -(-cos^{2}x)$ = 1

In [20]:
a = np.array([[4, 2, 3], [0, 5, 1], [0, 0, 9]])
print(f'Матрица:\n{a}')
print(f'Определитель:\n{np.linalg.det(a):.0f}')

Матрица:
[[4 2 3]
 [0 5 1]
 [0 0 9]]
Определитель:
180


In [21]:
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f'Матрица:\n{b}')
print(f'Определитель:\n{np.linalg.det(b):.0f}')

Матрица:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Определитель:
0



__2.__ Определитель матрицы $A$ равен $4$. Найти:

   а) $det(A^{2})$;
    
   б) $det(A^{T})$;
    
   в) $det(2A)$.
   

 $det(A^{2})$ = det(A) det(A) = 16

$det(A^{T})$= det(A) = 4

det(2A) = $2^{2}$ det(A) = 16


__3.__  Доказать, что матрица

$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$
   
вырожденная.

In [22]:
A = np.matrix('-2, 7, -3; 4, -14, 6; -3, 7, 13')
print(f'Ранг матрицы равен {rank(A)}')
try:
  print(f'Обратная матрица {inv(A)}')
except:
  print('Нет обратной матрицы')

Ранг матрицы равен 2
Нет обратной матрицы


Ранг матрицы меньше числа ее строк, и у нее отсутствует обратная матрица следовательно матреца вырождена


__4.__ Найти ранг матрицы:

   а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix};$

   б) $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}.$

In [23]:
A = np.matrix('1, 2, 3; 1, 1, 1; 2, 3, 4')
r = np.linalg.matrix_rank(A)
print(f'Ранг матрицы: {r}')

Ранг матрицы: 2


In [24]:
B = np.matrix('0, 0, 2, 1; 0, 0, 2, 2; 0, 0, 4, 3; 2, 3, 5, 6')
r = np.linalg.matrix_rank(B)
print(f'Ранг матрицы: {r}')

Ранг матрицы: 3
